# Generated by Django 2.2.1 on 2019-10-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
    	migrations.RunSQL("alter table monitoramento_registro alter column data_acesso set default current_timestamp")
    ]
