# Generated by Django 2.2.1 on 2019-08-27 23:13

from django.db import migrations

#Esta classe é responsável por alterar o valor padrão da coluna data_acesso pois o django por padrão não define um valor default.
class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("alter table monitoramento_registro alter column data_acesso set default current_timestamp")
    ]
